"""
Merge Tracking Data with Qualtrics Survey Data

Joins the tracking events (from Supabase export) with the token mapping
and Qualtrics survey responses to produce a respondent × month panel
dataset ready for econometric analysis.

Usage:
    python merge_data.py <qualtrics_export.csv>

Inputs:
    - tokens/token_map.csv           (generated by generate_tokens.py)
    - tracking/tracking_events.csv   (exported by export_tracking.py)
    - <qualtrics_export.csv>         (original Qualtrics survey export)

Output:
    analysis/analysis_panel.csv
"""

import sys
import pandas as pd
from pathlib import Path


def main():
    if len(sys.argv) < 2:
        print("Usage: python merge_data.py <qualtrics_export.csv>")
        sys.exit(1)

    project_root = Path(__file__).parent.parent
    qualtrics_path = sys.argv[1]

    # Load data
    tokens = pd.read_csv(project_root / "tokens" / "token_map.csv")
    events = pd.read_csv(project_root / "tracking" / "tracking_events.csv")
    qualtrics = pd.read_csv(qualtrics_path)

    # Merge tokens into events
    events_with_id = events.merge(
        tokens[["token", "qualtrics_response_id"]],
        on="token",
        how="inner"
    )

    # Construct engagement variables per respondent per report month
    engagement = (
        events_with_id
        .groupby(["qualtrics_response_id", "report_month"])
        .agg(
            opened=("event_type", lambda x: int((x == "opened").any())),
            downloaded=("event_type", lambda x: int((x == "downloaded").any())),
            total_seconds=("duration_seconds", "max"),
            num_visits=("event_type", lambda x: int((x == "opened").sum())),
        )
        .reset_index()
    )

    # Merge with Qualtrics survey data
    if "ResponseId" in qualtrics.columns:
        qualtrics = qualtrics.rename(columns={"ResponseId": "qualtrics_response_id"})

    panel = qualtrics.merge(
        engagement,
        on="qualtrics_response_id",
        how="left"
    )

    # Fill NaN engagement variables with 0 for respondents with no tracking data
    for col in ["opened", "downloaded", "total_seconds", "num_visits"]:
        if col in panel.columns:
            panel[col] = panel[col].fillna(0).astype(int)

    output_path = project_root / "analysis" / "analysis_panel.csv"
    panel.to_csv(output_path, index=False)
    print(f"Panel dataset: {len(panel)} rows → {output_path}")


if __name__ == "__main__":
    main()
